version: '3'
services:
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
    networks:
      - melaa

  backend:
    container_name: backend
#    build: .
    image: app:latest

    ports:
      - "8080:8080"
    expose:
      - 8080
    environment:
#      - spring.datasource.url=jdbc:mysql://localhost:3306/store2?createDatabaseIfNotExist=true
#      - spring.datasource.password=root
#      - spring.datasource.username=root
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - melaa

  service-registry:
    container_name: registry
    image: registry:latest
    ports:
      - "8762:8761"
    expose:
      - 8762
    networks:
      - melaa

#  lb:
#    container_name: lb
#    image: lb:latest
#    ports:
#      - "9001:9000"
#    expose:
#      - 9000
#    networks:
#      - melaa


volumes:
  mysql-data:

networks:
  melaa:
    driver: bridge
