version: '3'
services:
  service-registry:
    container_name: registry
    image: registry:latest
    ports:
      - "8761:8761"
    expose:
      - 8761
    networks:
      - melaa

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
    networks:
      - melaa

  backend:
#    build: .
    image: backend:latest
    depends_on:
      - service-registry

    deploy:
      replicas: 3
    expose:
      - 8080
    environment:
#      - spring.datasource.url=jdbc:mysql://localhost:3306/store2?createDatabaseIfNotExist=true
#      - spring.datasource.password=root
#      - spring.datasource.username=root
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - melaa



  lb:
    container_name: lb
    image: lb:latest
    ports:
      - "9000:9000"
    expose:
      - 9000
    depends_on:
      - backend
    networks:
      - melaa


volumes:
  mysql-data:

networks:
  melaa:
    driver: bridge
