version: '3'
services:
  registry:
    container_name: registry
    image: waralgorithmspace2/registry:latest
    ports:
      - "8761:8761"
    expose:
      - 8761
    networks:
      - melaa

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
    networks:
      - melaa

  backend:
#    build: .
    image: waralgorithmspace2/backend:latest
    depends_on:
      - registry
    ports:
      - "8081-8083:8080"
    deploy:
      mode: replicated
      replicas: 3
    environment:
#      - spring.datasource.url=jdbc:mysql://103.104.183.122:3306/store2?createDatabaseIfNotExist=true
#      - spring.datasource.password=root
#      - spring.datasource.username=root
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - mysql-data:/app/image
    networks:
      - melaa

  lb:
    container_name: lb
    image: waralgorithmspace2/lb:latest
    ports:
      - "9000:9000"
    expose:
      - 9000
    depends_on:
      - registry
      - backend
    networks:
      - melaa


volumes:
  mysql-data:

networks:
  melaa:
    driver: bridge
