
version: '3'
services:
  registry:
    container_name: registry
    image: waralgorithmspace2/registry:latest
    ports:
      - "8761:8761"
    expose:
      - 8761
    networks:
      - melaa

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
    networks:
      - melaa

  backend:
    #    build: .
    image: waralgorithmspace2/backend:latest
    depends_on:
      - registry
    ports:
      - "8081-8083:8080"
    deploy:
      mode: replicated
      replicas: 3
    environment:
      #      - spring.datasource.url=jdbc:mysql://localhost:3306/store2?createDatabaseIfNotExist=true
      #      - spring.datasource.password=root
      #      - spring.datasource.username=root
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - mysql-data:/app/image

    networks:
      - melaa

  lb:
    container_name: lb
    image: waralgorithmspace2/lb:latest
    ports:
      - "9000:9000"
    expose:
      - 9000
    depends_on:
      - registry
      - backend
    networks:
      - melaa
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CLI_ARGS= #optional
    volumes:
      - /path/to/appdata/config:/config
      - /path/to/backups:/backups
      - /path/to/source:/source
    ports:
      - 8200:8200
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data



volumes:
  mysql-data:
  portainer_data:


networks:
  melaa:
    driver: bridge
