server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: melaa
  datasource:
    initialization-mode: always
    username: root
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    password: root
  jpa:
    defer-datasource-initialization: true
    sql:
      init:
        mode: always
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  main:
    banner-mode: 'off'
  profiles:
    active:

fcm:
  service-account-file: src/main/resources/baba-basket-645b9-firebase-adminsdk-zyteh-7b351169bd.json


hibernate:
  hbm2ddl:
    auto: update
jwt:
  secret: javainuse

#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${random.uuid}
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    loggers:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

  metrics:
    export:
      prometheus:
        enabled: true
  main:
    banner-mode: 'off'


redis:
  host: localhost
  port: 6379

melaa:
  storage:
#    type: s3
    type: file
  storagePath: C:/Users/Dell/Pictures/product_image/
  master: 7759856927
  category:
    id: 1
  product:
    image-path: C:/Users/Dell/Desktop/store/image/drink
  roles: ADMIN,MASTER,SELLER,CUSTOMER,DELIVERY
  orderStatus: SEND_TO_SHOP,PLACED,ACCEPTED,DISPATCHED,ON_THE_WAY,DELIVERED,CANCELED_DUE_TO_OUT_OF_STOCK,FAILED_DUE_TO_TECHNICAL_ISSUE,CANCELED,RETURN_INITIATED,REFUNDED
  shopType: GROCERY_RETAILS,STATIONARY,GROCERY_WHOLESALES,SPICE_SHOP,GENERAL_STORE,SWEETS_SHOP
  deleteUserOrderBatchSize: 50

properties:
  deliveryHr: 1,2,3,4,5,6
  orderMoreThan: 500
  shippingCharge: 30

cloud:
  aws:
    bucketName: melaa-img
    credentials:
      access-key: AKIATO6E6SX7NDJKP6KD
      secret-key: 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
    region:
      static: ap-south-1
    stack:
      auto: false