fcm:
  service-account-file: src/main/resources/baba-basket-645b9-firebase-adminsdk-zyteh-7b351169bd.json
hibernate:
  hbm2ddl:
    auto: update


jwt:
  secret: javainuse
management:
  endpoint:
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: loggers
server:
  port: 1080
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: root

    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
  main:
    banner-mode: 'off'