server:
  port: 1080
spring:
  application:
    name: melaa

  datasource:
    initialization-mode: always
    password: root
#    password: YIqfJBkVtz6QP0tgI4Fq
#    url: jdbc:mysql://db.cwdsaavl8v7o.ap-south-1.rds.amazonaws.com:3306/store?createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
#    username: admin
    username: root
  jpa:
    defer-datasource-initialization: true
    sql:
      init:
        mode: always
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  main:
    banner-mode: 'off'
  profiles:
    active:
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


fcm:
  service-account-file: src/main/resources/baba-basket-645b9-firebase-adminsdk-zyteh-7b351169bd.json


hibernate:
  hbm2ddl:
    auto: update
jwt:
  secret: javainuse
management:
  endpoint:
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: loggers


redis:
  host: localhost
  port: 6379

melaa:
  category:
    id: 1
  product:
    image-path: C:/Users/Dell/Desktop/store/image/drink




properties:
  deliveryHr: 1,2,3,4,5,6
  orderMoreThan: 500
  shippingCharge: 30