server:
  address: 0.0.0.0
  port: 8080
spring:
  application:
    name: melaa
  datasource:
    initialization-mode: always
    username: user
    #    password: YIqfJBkVtz6QP0tgI4Fq
    #    url: jdbc:mysql://db.cwdsaavl8v7o.ap-south-1.rds.amazonaws.com:3306/store?createDatabaseIfNotExist=true
    url: jdbc:mysql://154.49.243.177:3306/store?createDatabaseIfNotExist=true
    #    username: admin
    password: P@ssW0rd
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
management:
  endpoint:
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: loggers
  main:
    banner-mode: 'off'




fcm:
  service-account-file: baba-basket-645b9-firebase-adminsdk-zyteh-7b351169bd.json


hibernate:
  hbm2ddl:
    auto: update
jwt:
  secret: javainuse

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

melaa:
  storage:
#    type: s3
    type: file
  master: 7759856927
  storagePath: /app/image/
  getImagePath: /app/image/
  category:
    id: 1
  deliveryHr: 1,2,3,4,5,6,24,48,100
  product:
    image-path: C:/Users/Dell/Desktop/store/image/drink
  roles: ADMIN,MASTER,SELLER,CUSTOMER,DELIVERY
  orderStatus: SEND_TO_SHOP,PLACED,ACCEPTED,DISPATCHED,ON_THE_WAY,DELIVERED,CANCELED_DUE_TO_OUT_OF_STOCK,FAILED_DUE_TO_TECHNICAL_ISSUE,CANCELED,RETURN_INITIATED,REFUNDED
  shopType: GROCERY_RETAILS,STATIONARY,GROCERY_WHOLESALES,SPICE_SHOP,GENERAL_STORE,SWEETS_SHOP



cloud:
  aws:
    bucketName: melaa-img
    credentials:
      access-key: AKIATO6E6SX7NDJKP6KD
      secret-key: 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
    region:
      static: ap-south-1
    stack:
      auto: false